-- מיגרציה 002: טבלת התלמידים של רשות 1400000 (אפיון §3)
-- טבלה ראשית ייחודית לרשות. נדרסת בכל עדכון חודשי. אינדקס ראשי: תעודת זהות.
-- זהו התבנית ("template") — לכל רשות נוספת יוצרים טבלה זהה בשם students_{code}
-- ומדיניות RLS המפנה ל-has_authority('{code}').
-- שמות העמודות תואמים ל-python_name של ה-pipeline (מודול 7 מייצר אותם).

create table if not exists public.students_1400000 (
  "KITA_MESHULEVET" text,
  "STATUS_CHINUCH_MEYUCHAD" text,
  "STATUS_TALMID_BARASHUT" text,
  "MUTAV" text,
  "RASHUT_CHINUCH_MOSAD" text,
  "RASHUT_CHINUCH_TEUR" text,
  "SHEM_MOSAD" text,
  "SUG_MOSAD_TEUR" text,
  "SHEM_YISHUV" text,
  "KTOVET_MOSAD" text,
  "TELEFON_MOSAD" text,
  "GOREM_MEDAVEACH_TEUR" text,
  "MIGZAR_TEUR" text,
  "MAAMAD_MISHPATI_TEUR" text,
  "SUG_PIKUACH_TEUR" text,
  "SUG_CHINUCH_TEUR" text,
  "SHLAV_HINUCH_TEUR" text,
  "SUG_ZEHUT" text,
  "MISPAR_ZEHUT" text primary key,
  "MISPAR_DARKON" text,
  "KVUTSAT_DARKON" text,
  "SHEM_MISHPACHA" text,
  "SHEM_PRATI" text,
  "SHEM_MISHPACHA_KINUI" text,
  "SHEM_PRATI_KINUI" text,
  "CODE_MIN" text,
  "CODE_LEOM_PNIM" text,
  "CODE_ERETS_LEDA" text,
  "CODE_ERETS_ALIYA" text,
  "TAARICH_LEDA" date,
  "TAARICH_ALIYA" date,
  "MISPAR_ACHIM_AD_18" numeric,
  "SHICHVA" text,
  "MAKBILA" text,
  "CODE_SUG_KITA" text,
  "TEUR_SUG_KITA" text,
  "TEUR_STATUS_ISHUR" text,
  "TAARICH_STATUS_ISHUR_KITA" date,
  "MIN_TALMIDIM" numeric,
  "MAX_TALMIDIM" numeric,
  "CODE_MASLUL" text,
  "CODE_NATIV" text,
  "CODE_HASMACHA" text,
  "SEMEL_MEGAMA_MISRAD_x" text,
  "TEUR_MEGAMA_MISRAD" text,
  "SEMEL_MEGAMA_MOSAD" text,
  "SHEM_MEGAMA_MOSAD" text,
  "MICHSAT_TALMIDIM_MEVUKESHET" numeric,
  "TEUR_STATUS_ISHUR_MEGAMA" text,
  "CODE_STATUS_RISHUM_TA" text,
  "TEUR_SIBAT_AZIVA" text,
  "PIRUT_AZIVA" text,
  "TAARICH_CHAZARA_MCHUL" date,
  "SHNOT_LIMUD_BCHUL" numeric,
  "MISPAR_ZEHUT_KODEMET" text,
  "SUG_ZEHUT_KODEMET" text,
  "TAARICH_IDKUN_RESHUMA" date,
  "HAIM_RASHUT_ACHERET" text,
  "SEMEL_YISHUV1" text,
  "TEUR_YISHUV1" text,
  "SHEM_RECHOV1" text,
  "MISPAR_BAYIT1" text,
  "MISPAR_DIRA1" text,
  "SEMEL_YESHUV2" text,
  "TEUR_YESHUV2" text,
  "SHEM_RECHOV2" text,
  "MISPAR_BAIT2" text,
  "KNISA2" text,
  "MISPAR_DIRA2" text,
  "TA_DOAR2" text,
  "MIKUD2" text,
  "SHCHUNA2" text,
  "HEARA2" text,
  "DOAR_NA2" text,
  "GOREM_KESHER_1_ID" text,
  "GOREM_KESHER_1_SUG_ZEHUT" text,
  "GOREM_KESHER_1_CODE_SUG_KIRVA" text,
  "GOREM_KESHER_1_Family_Name" text,
  "GOREM_KESHER_1_LEKABEL_MEIDA" text,
  "GOREM_KESHER_1_HAIM_MESHALEM" text,
  "GOREM_KESHER_1_CODE_MAAMAD_HORE" text,
  "EMAIL_parent1" text,
  "GOREM_KESHER_2_ID" text,
  "GOREM_KESHER_2_SUG_ZEHUT" text,
  "GOREM_KESHER_2_CODE_SUG_KIRVA" text,
  "GOREM_KESHER_2_Name" text,
  "GOREM_KESHER_2_LEKABEL_MEIDA" text,
  "GOREM_KESHER_2_HAIM_MESHALEM" text,
  "GOREM_KESHER_2_CODE_MAAMAD_HORE" text,
  "MIKUD7_parent2" text,
  "TEUR_YESHUV2_parent2" text,
  "SHCHUNA2_parent2" text,
  "SHEM_RECHOV2_parent2" text,
  "MISPAR_BAIT2_parent2" text,
  "MISPAR_DIRA2_parent2" text,
  "MIKUD2_parent2" text,
  "KNISA2_parent2" text,
  "TA_DOAR2_parent2" text,
  "HEARA2_parent2" text,
  "DOAR_NA2_parent2" text,
  "SHNAT_LIMUDIM" text,
  "SEMEL_MOSAD" text,
  "RASHUT_TALMID" text,
  "TKINUT_SHIBUTZ" text,
  "LO_LE_DIVUACH_MATZEVET" text,
  "CODE_ZAKAUT_LSCHAR_LIMUD" text,
  "TAARICH_HATCHALA" date,
  "TAARICH_SIYUM" date,
  "TEUR_YISHUV1_parent1" text,
  "SHEM_RECHOV1_parent1" text,
  "MISPAR_BAYIT1_parent1" text,
  "MISPAR_DIRA1_parent1" text,
  "MIKUD7_parent1" text,
  "GOREM_KESHER_1_FULL_NAME" text,
  "GOREM_KESHER_2_FULL_NAME" text,
  "HAIM_PIRTEY_KESHER_TALMID" text,
  "HAIM_PIRTEY_KESHER_TALMID_parent1" text
);

-- אינדקסים לזיהוי אחים (חיפוש לפי ת.ז. הורה) ולסינון נפוץ
create index if not exists idx_students_1400000_parent1 on public.students_1400000 ("GOREM_KESHER_1_ID");
create index if not exists idx_students_1400000_parent2 on public.students_1400000 ("GOREM_KESHER_2_ID");
create index if not exists idx_students_1400000_mosad on public.students_1400000 ("SEMEL_MOSAD");

-- RLS: רק משתמשים המשויכים לרשות 1400000 רשאים לקרוא
alter table public.students_1400000 enable row level security;

drop policy if exists students_1400000_read on public.students_1400000;
create policy students_1400000_read on public.students_1400000
  for select to authenticated using (public.has_authority('1400000'));

-- רישום הרשות במטא-טבלה
insert into public.authorities (code, name)
values ('1400000', 'מטה מנשה')
on conflict (code) do nothing;
